VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "base"
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"
  config.vm.hostname = "jenkins"
  config.vm.network "private_network", ip: "10.10.10.2"
  config.vm.synced_folder "../", "/var/devoxx-2014-mepc/"
  config.vm.provision "puppet" do |puppet|
    puppet.options = "--verbose --debug"
  end
  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end
end
